"""add user_id to tasks and remove ip_address

Revision ID: 20260420_0003
Revises: 20260420_0002
Create Date: 2026-04-20 00:03:00.000000

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = "20260420_0003"
down_revision = "20260420_0002"
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    # Drop the ip_address index first if it exists
    try:
        op.drop_index("ix_tasks_ip_address", table_name="tasks")
    except:
        pass
    
    # Drop the ip_address column
    try:
        op.drop_column("tasks", "ip_address")
    except:
        pass
    
    # Add user_id column (nullable to allow existing data)
    op.add_column("tasks", sa.Column("user_id", sa.Integer(), nullable=True))
    
    # Create foreign key constraint
    op.create_foreign_key("fk_tasks_user_id", "tasks", "users", ["user_id"], ["id"])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    # Add back ip_address column
    op.add_column("tasks", sa.Column("ip_address", sa.String(45), nullable=False))
    op.create_index("ix_tasks_ip_address", "tasks", ["ip_address"])
    
    # Remove user_id
    op.drop_constraint("fk_tasks_user_id", "tasks", type_="foreignkey")
    op.drop_column("tasks", "user_id")
    # ### end Alembic commands ###
